version: '3'

services:

  ordering:
    build: ordering
    depends_on:
      - air
      - sea
      - ground
      - space
    ports:
      - "8084:8084"


  quotations:
    build: quotations
    depends_on:
      - air
      - sea
      - ground
      - space
    ports:
      - "8083:8083"

  tracking:
    build: tracking
    depends_on:
      - air
      - sea
      - ground
      - space
    ports:
      - "8085:8085"

  air:
    build: air

  sea:
    build: sea

  ground:
    build: ground

  space:
    build: space
